version: '2.3'
services:
  db:
    image: postgres:10
  redis:
    image: redis:3.2
  server:
    build: .
    image: francisli/voterguides
    command: bash -l -c "rm -f /opt/rails/app/tmp/pids/server.pid; foreman start"
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:@db:5432/voterguides_development
      - DATABASE_TEST_URL=postgresql://postgres:@db:5432/voterguides_test
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=1
    ports:
      - '${HOST_PORT:-3000}:3000'
    depends_on:
      - db
      - redis
