version: '2.3'
services:
  mailcatcher:
    image: tikitaki/public:mailcatcher
    command: /usr/local/bundle/bin/mailcatcher -f --ip 0.0.0.0
    ports:
      - '1080:1080'
  server:
    command: bash -l -c "rm -f /opt/rails/app/tmp/pids/server.pid; foreman start -f Procfile.development"
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    volumes:
      - .:/opt/rails/app
      - /opt/rails/app/node_modules
    ports:
      - '3035:3035'
    depends_on:
      - mailcatcher
